# This file contains a list of the credentials and attributes of those credentials to be issued by this issuer.
# To add a new credential, copy and paste the existing one and edit away.
# On startup, the VON Issuer/Verifier Agent will publish the schema and credential definitions to the ledger for each defined credential

- name: my-permit.my-organization.ca
  # The version of the credential. Update this if you want to publish a new version of the credential schema
  version: '1.0.0'
  description: my-permit Credential issued by my-organization.ca
  # URL mapping, e.g. /path/credential
  path: /my-organization/my-permit
  # Topic: The attribute from the list below which identifies the owning organization
  topic: registration_id
  # Cardinality: Any additional attributes from the list below that uniquely identifies an instance of this credential
  #     When a credential with the same values in the topic and optional cardinality attributes is received, 
  #     the previous credential is marked as "revoked".
  # cardinality: <add here>
  # The attribute to be used by TOB as the effective date of the credential
  effective_date: effective_date
  # The attribute to be used by TOB as the expiration date of the credential
  # revoked_date: expiry_date
  # The proof request upon which the application for this Credential is dependent
  # An organization must satisfy this proof request before they can apply for this credential
  proof_request: permitify_registration
  # Attributes are claims indexed in TheOrgBook for use in the UI
  # For each, data_type is one of:
  #      ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
  attributes:
    registration_id:
      description: ID of the organization to be issued a permit-name Credential
      data_type: ui_text
      required: true
    legal_name:
      description: Legal name of the organization
      data_type: ui_name
      required: true
    permit_id:
      description: ID of the permit-name issued by my-organization
      data_type: helper_uuid
      required: true
    permit_type:
      description: Type of the permit-name 
      data_type: ui_select
      required: true
    permit_issued_date:
      description: Permit date (set to current date)
      data_type: helper_now_iso
      required: true
    permit_status:
      description: Permit status (set to active)
      data_type: helper_vlue
      required: true
    effective_date:
      description: Date credential is effective
      data_type: ui_date
      required: true


#################################################################
# TODO insert additional credential schema here:

#################################################################

### eof ###

