- name: myorg-registration.my-organization.ca
  version: '1.0.0'
  description: Describes the credential
  path: URL mapping, e.g. /path/credential
  topic: identify the attribute which identify the owning organization
  cardinality: optionally identify additional attributes to uniquely identify a credential
  effective_date: optionally identify the credential attribute to map to the TOB credential effective date
  revoked_date: optionally identify the credential attribute to map to the TOB credential revoked date
  proof_request: optionally identify a dependant proof request
  attributes:
    registration_id:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    registration_date:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    entity_type:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    entity_status:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    entity_status_effective:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    entity_name_effective:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    address_line_1:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    address_line_2:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    addressee:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    city:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    country:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    legal_name:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    postal_code:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    province:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    effective_date:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    expiry_date:
      description: Date Credential expires (typically same as next version of credential is issued)
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: false

- name: myorg-tax.my-organization.ca
  version: '1.0.0'
  attributes:
    registration_id:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    tax_number:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    effective_date:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true

- name: myorg-liquor.my-organization.ca
  version: '1.0.0'
  attributes:
    registration_id:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    license_number:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    dancing_permitted:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    patio:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    effective_date:
      description: TBD
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    expiry_date:
      description: Date Credential expires (typically same as next version of credential is issued)
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: false

- name: myorg-credential.my-organization.ca
  version: '1.0.0'
  attributes:
    registration_id:
      description: Unique identifer assigned to entity by registrar (requires an existing registration credential)
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    tax_number:
      description: Relevant tax number
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    license_number:
      description: Relevant liquor license number
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    credential_status:
      description: Status of the credential (ACTive or HIStorical)
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    credential_status_effective:
      description: Date status became/becomes effective (e.g. can be future dated)
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    credential_status_expiry:
      description: Date status will expire
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: false
    effective_date:
      description: Date Credential is effective (typically same as date credential is issued)
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: true
    expiry_date:
      description: Date Credential expires (typically same as next version of credential is issued)
      data_type: name, address, attr_text, attr_date
      source: ui_text, ui_address, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      required: false

