issuers:
  myorg:
    name: my-org-full-name
    abbreviation: my-organization
    url: https://www.my-organization.ca/my-organization-info-page
    email: info@my-organization.ca
    logo_path: ../assets/img/my-organization-logo.jpg
    endpoint: $ENDPOINT_URL

    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
      sign_target: false

    wallet:
      name: ${POSTGRESQL_WALLET_NAME:-myorg_issuer}
      seed: $WALLET_SEED_VONX
      type: $WALLET_TYPE
      params:
        storage_config:
          url: "$POSTGRESQL_WALLET_HOST:$POSTGRESQL_WALLET_PORT"
      access_creds:
        key: $WALLET_ENCRYPTION_KEY
        storage_credentials:
          account: $POSTGRESQL_WALLET_USER
          password: $POSTGRESQL_WALLET_PASSWORD
          admin_account: ${POSTGRESQL_WALLET_ADMIN_USER:-postgres}
          admin_password: $POSTGRESQL_WALLET_ADMIN_PASSWORD
        key_derivation_method: ARGON2I_MOD

    credential_types:
    - description: Permit
      schema: my-permit.my-organization.ca
      issuer_url: http://localhost:5001/my-organization/my-permit
      depends_on:
        - permitify_registration
      # define credential meta-data
      # maps attributes provided in the credential to TOB's credential effective and revoked dates
      # if not provided TOB will set effective and expiry dates based on current date
      credential:
        effective_date:
          input: effective_date
          from: claim
      # identifies the organization id that owns the credential
      # "topic" is used as a more generic term since the platform can be used for entities other than organizations
      # in our deployment the type is always "registration"
      topic:
        source_id:
          input: corp_num
          from: claim
        type:
          input: registration
          from: value
      # optional - specify additional cardinality fields
      #cardinality_fields:
      #  - additionl_cred_type_attr
      # mapping to the TOB data model - can map to name, address or a generic attribute
      mapping:
        # "name" is a known mapping; "legal_name" is a known field name
        - model: name
          fields:
            text:
              input: legal_name
              from: claim
            type:
              input: legal_name
              from: value
        # "address" is a special mapping that creates a series of fields in the model
        # - model: address
        #   fields:
        #     addressee:
        #       input: addressee
        #       from: claim
        #     civic_address:
        #       input: address_line_1
        #       from: claim
        #     city:
        #       input: city
        #       from: claim
        #     province:
        #       input: province
        #       from: claim
        #     postal_code:
        #       input: postal_code
        #       from: claim
        #     country:
        #       input: country
        #       from: claim
        # "attribute" defines a generic field in the TOB model
        # "value" identifies where to derive the data value (typically it comes from the claim)
        # "type" - if "value" - is the name of the attribute
        # "format" is an optional data format (default text)
        - model: attribute
          fields:
            type:
              input: permit_issued_date
              from: value
            format:
              input: datetime
              from: value
            value:
              input: permit_issued_date
              from: claim
        - model: attribute
          fields:
            type:
              input: permit_type
              from: value
            value:
              input: permit_type
              from: claim
        - model: attribute
          fields:
            type:
              input: permit_status
              from: value
            value:
              input: permit_status
              from: claim
        - model: attribute
          fields:
            type:
              input: effective_date
              from: value
            format:
              input: datetime
              from: value
            value:
              input: effective_date
              from: claim


#################################################################
# TODO insert new service here, note should align like:
#   credential_types:
#   - description: Registration

#################################################################

verifiers:
  bctob:
    name: BC OrgBook
    connection:
      type: TheOrgBook
      api_url: $TOB_API_URL
    wallet:
      seed: "tob-verifier-wallet-000000000001"

proof_requests:
  # Your DID - for proof requests based on this Issuer's Credentials
  #      X3tCbZSE9uUb223KYDWd6o
  permitify_registration:
    version: '1.0.0'
    schemas:
      - key:
          did: 6qnvgJtqwK44D8LFYnV5Yf
          name: registration.dflow
          version: '1.0.1'
        attributes:
          - corp_num
          - legal_name


### eof ###
