- name: todo-rename-me3.my-organization.ca
  version: '1.0.0'
  description: Describes the credential - depends on myorg foundation credential
  # URL mapping, e.g. /path/credential
  path: /myorg/todo-credential
  # identify the attribute which identify the owning organization
  topic: registration_id
  # optionally identify additional attributes to uniquely identify a credential
  cardinality: credential_subtype
  # optionally identify the credential attribute to map to the TOB credential effective date
  effective_date: effective_date
  # optionally identify the credential attribute to map to the TOB credential revoked date
  revoked_date: expiry_date
  # optionally identify a dependant proof request
  proof_request: registration
  attributes:
    registration_id:
      description: Unique identifer assigned to entity by registrar (requires an existing registration credential)
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    credential_id:
      description: Some internal generated credential id
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: helper_uuid
      required: true
    credential_subtype:
      description: Subtype of the credential (for supporting cardinality)
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_select
      required: true
    credential_text:
      description: Some random text about the credential
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_text
      required: true
    credential_status:
      description: Status of the credential (ACTive or HIStorical)
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_select
      required: true
    effective_date:
      description: Date Credential is effective (typically same as date credential is issued)
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: true
    expiry_date:
      description: Date Credential expires (typically same as next version of credential is issued)
      # one of: ui_name, ui_address, ui_text, ui_date, ui_select, helper_uuid, helper_now_iso, helper_value
      data_type: ui_date
      required: false
