myorgtodo-credential:
  path: /myorg/todo-credential
  type: issue-credential
  schema_name: toto-rename-me.my-organization.ca
  page_title: Title for toto-rename-me.my-organization.ca
  title: Title for toto-rename-me.my-organization.ca
  template: bcgov.index.html
  description: Describes the credential - depends on permitifys foundation credential
  explanation: Use the form below to issue a Credential.
  proof_request:
    id: permitify_registration
    connection_id: bctob
  fields:
  - name: corp_num
    label: corp_num
    type: text
    required: true
  - name: credential_text
    label: credential_text
    type: text
    required: true
  - name: credential_status
    label: credential_status
    type: select
    required: true
  - name: effective_date
    label: effective_date
    type: date
    required: true
  - name: expiry_date
    label: expiry_date
    type: date
    required: false
  mappings:
    attributes:
    - name: credential_id
      from: helper
      source: uuid
